version: "3.8"
services:
  postgresql-db:
    image: postgres:latest
    volumes:
      - ./data/db:/var/lib/postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
    ports:
      - "5433:5432"
  app:
    container_name: proyecto_tingeso
    image: jeremylm10748/proyecto_tingeso
    ports:
      - "8090:8090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql-db:5432/postgres?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345678
      SPRING_PROFILES_ACTIVE: docker
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - postgresql-db

